# Generated by Django 3.2.13 on 2022-04-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag',
        ),
    ]
